### PR TITLE
fixup tox and travis configs

### PR DESCRIPTION
**Pull request by benmaddison**
addressing issues: #14 and #13

### CODE REVIEW

**Comment by vegu** [comment]
Thanks once more, merging.

**Comment by benmaddison** [comment]
no worries @vegu. would you push a release pls?

**Comment by vegu** [comment]
@benmaddison absolutely, will do so in a bit

**Comment by vegu** [comment]
@benmaddison done, tagged at 0.7.0 and released to pypi as well

**Pull request merged**
